aws_profile                  = "custom"
bigbluebutton_domain_name    = "example.com"
bigbluebutton_subdomain_name = "test"
scalelite_domain_name        = "example.com"
scalelite_subdomain_name     = "lb"