- hosts: bigbluebutton
  become: yes
  tasks:
  - name: Download bbb-install.sh
    get_url:
      url: https://ubuntu.bigbluebutton.org/bbb-install.sh
      dest: /bbb-install.sh
      mode: 0700
  - name: Include variables file
    include_vars:
      file: bigbluebutton_vars.yaml
  - name: Run bbb-install.sh
    command: /bin/bash /bbb-install.sh -v xenial-22 -s {{ url_host }} -e {{ email }} -w
  - name: Delete bbb-install.sh
    file: 
      path: /bbb-install.sh 
      state: absent